CLOUD_DB_URL=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres?currentSchema=logistics
CLOUD_DB_USER=postgres.mcszberajsrnyafpogto
CLOUD_DB_PASSWORD=A6aAGUMe8v&r-M=
JWT_SECRET=NWEN+d4oEI7Mfk4GYu1IhG/nK2qMKqGPy3aOkwco0pA=
JWT_EXPIRATION=86400000